name: Python package
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_PASSWORD }}